export const APP_TITLE = 'drunkBSD.io';
export const APP_DESCRIPTION = 'Battle of dying programs inside a corrupted BSD distro to keep itself running';
export const MAP_WIDTH = 10000;
export const MAP_HEIGHT = 10000;
export const MAP_BACKGROUND_COLOR_HEX = 0x019767;
export const CELL_WIDHT_IN_PX = 50;
export const CELL_HEIGHT_IN_PX = 50;
export const MAX_HORIZONTAL_CELL = MAP_WIDTH / CELL_WIDHT_IN_PX;
export const MAX_VERTICAL_CELL = MAP_HEIGHT / CELL_HEIGHT_IN_PX;
